In [1]:
import pandas as pd
import numpy as np
#df_org=pd.read_csv(filepath+"application_train_merge_clear_nomissing .csv")
df_org=pd.read_csv("application_train_merge_clear_nomissing_with_ylabel.csv")

In [2]:
df=df_org

In [8]:
df.columns.tolist()

['SK_ID_CURR',
 'TARGET',
 'CNT_CHILDREN',
 'AMT_INCOME_TOTAL',
 'NAME_EDUCATION_TYPE',
 'DAYS_BIRTH',
 'DAYS_EMPLOYED',
 'DAYS_REGISTRATION',
 'DAYS_ID_PUBLISH',
 'FLAG_EMP_PHONE',
 'FLAG_WORK_PHONE',
 'FLAG_PHONE',
 'FLAG_EMAIL',
 'CNT_FAM_MEMBERS',
 'HOUR_APPR_PROCESS_START_x',
 'REG_REGION_NOT_LIVE_REGION',
 'REG_REGION_NOT_WORK_REGION',
 'LIVE_REGION_NOT_WORK_REGION',
 'REG_CITY_NOT_LIVE_CITY',
 'REG_CITY_NOT_WORK_CITY',
 'LIVE_CITY_NOT_WORK_CITY',
 'OBS_60_CNT_SOCIAL_CIRCLE',
 'DEF_60_CNT_SOCIAL_CIRCLE',
 'DAYS_LAST_PHONE_CHANGE',
 'AMT_REQ_CREDIT_BUREAU_HOUR',
 'AMT_REQ_CREDIT_BUREAU_WEEK',
 'AMT_REQ_CREDIT_BUREAU_MON',
 'AMT_REQ_CREDIT_BUREAU_QRT',
 'AMT_REQ_CREDIT_BUREAU_YEAR',
 'NAME_CONTRACT_TYPE_Cash loans',
 'NAME_CONTRACT_TYPE_Revolving loans',
 'CODE_GENDER_F',
 'CODE_GENDER_M',
 'FLAG_OWN_CAR_N',
 'FLAG_OWN_CAR_Y',
 'FLAG_OWN_REALTY_N',
 'FLAG_OWN_REALTY_Y',
 'NAME_TYPE_SUITE_Children',
 'NAME_TYPE_SUITE_Family',
 'NAME_TYPE_SUITE_Spouse, partner',
 'NAME_TYPE_SUITE_Unaccompanied',
 'NAME_INCOME_TYPE_Commercial associate',
 'NAME_INCOME_TYPE_Pensioner',
 'NAME_INCOME_TYPE_State servant',
 'NAME_INCOME_TYPE_Working',
 'NAME_FAMILY_STATUS_Civil marriage',
 'NAME_FAMILY_STATUS_Married',
 'NAME_FAMILY_STATUS_Separated',
 'NAME_FAMILY_STATUS_Single / not married',
 'NAME_FAMILY_STATUS_Widow',
 'NAME_HOUSING_TYPE_House / apartment',
 'NAME_HOUSING_TYPE_Municipal apartment',
 'NAME_HOUSING_TYPE_Office apartment',
 'NAME_HOUSING_TYPE_Rented apartment',
 'NAME_HOUSING_TYPE_With parents',
 'OCCUPATION_TYPE_Accountants',
 'OCCUPATION_TYPE_Cleaning staff',
 'OCCUPATION_TYPE_Cooking staff',
 'OCCUPATION_TYPE_Core staff',
 'OCCUPATION_TYPE_Drivers',
 'OCCUPATION_TYPE_High skill tech staff',
 'OCCUPATION_TYPE_Laborers',
 'OCCUPATION_TYPE_Low-skill Laborers',
 'OCCUPATION_TYPE_Managers',
 'OCCUPATION_TYPE_Medicine staff',
 'OCCUPATION_TYPE_Private service staff',
 'OCCUPATION_TYPE_Sales staff',
 'OCCUPATION_TYPE_Security staff',
 'WEEKDAY_APPR_PROCESS_START_FRIDAY',
 'WEEKDAY_APPR_PROCESS_START_MONDAY',
 'WEEKDAY_APPR_PROCESS_START_SATURDAY',
 'WEEKDAY_APPR_PROCESS_START_SUNDAY',
 'WEEKDAY_APPR_PROCESS_START_THURSDAY',
 'WEEKDAY_APPR_PROCESS_START_TUESDAY',
 'WEEKDAY_APPR_PROCESS_START_WEDNESDAY',
 'ORGANIZATION_TYPE_Agriculture',
 'ORGANIZATION_TYPE_Bank',
 'ORGANIZATION_TYPE_Construction',
 'ORGANIZATION_TYPE_Government',
 'ORGANIZATION_TYPE_Housing',
 'ORGANIZATION_TYPE_Kindergarten',
 'ORGANIZATION_TYPE_Medicine',
 'ORGANIZATION_TYPE_Military',
 'ORGANIZATION_TYPE_Other',
 'ORGANIZATION_TYPE_Police',
 'ORGANIZATION_TYPE_Postal',
 'ORGANIZATION_TYPE_Restaurant',
 'ORGANIZATION_TYPE_School',
 'ORGANIZATION_TYPE_Security',
 'ORGANIZATION_TYPE_Security Ministries',
 'ORGANIZATION_TYPE_Self-employed',
 'ORGANIZATION_TYPE_Services',
 'ORGANIZATION_TYPE_XNA',
 'FONDKAPREMONT_MODE_not specified',
 'FONDKAPREMONT_MODE_org spec account',
 'FONDKAPREMONT_MODE_reg oper account',
 'FONDKAPREMONT_MODE_reg oper spec account',
 'HOUSETYPE_MODE_block of flats',
 'WALLSMATERIAL_MODE_Block',
 'WALLSMATERIAL_MODE_Mixed',
 'WALLSMATERIAL_MODE_Monolithic',
 'WALLSMATERIAL_MODE_Others',
 'WALLSMATERIAL_MODE_Panel',
 'WALLSMATERIAL_MODE_Stone, brick',
 'WALLSMATERIAL_MODE_Wooden',
 'EMERGENCYSTATE_MODE_No',
 'EMERGENCYSTATE_MODE_Yes',
 'SK_NUM_PREV',
 'NUM_INSTALMENT_VERSION',
 'DAYS_LATE_PAYMENT',
 'AMT_ARREARS',
 'PC_CNT_INSTALMENT_max',
 'PC_CNT_INSTALMENT_mean',
 'PC_SK_DPDMix_Max',
 'PC_SK_DPDMix_mean',
 'PC_Delay_total',
 'PC_Delay_mean',
 'PC_count',
 'PREV_ANNUITY_median',
 'PREV_APPLICATION_max',
 'PREV_CREDIT_max',
 'PREV_CREDIT_sum',
 'PREV_DOWN_PAYMENT_median',
 'PREV_GOODS_PRICE_max',
 'PREV_CRE/APP_max',
 'RATE_DOWN_PAYMENT_median',
 'RATE_INTEREST_PRIMARY_median',
 'RATE_INTEREST_PRIMARY_max',
 'DAYS_DECISION_median',
 'CNT_PAYMENT_median',
 'DAYS_PERIOD_median',
 'CONTRACT_Cash_loans',
 'CONTRACT_Consumer_loans',
 'CONTRACT_Revolving_loans',
 'Cash through the bank',
 'Non-cash from your account',
 'PORTFOLIO_Cards',
 'PORTFOLIO_Cash',
 'PORTFOLIO_POS',
 'YIELD_high',
 'YIELD_low',
 'YIELD_middle',
 'HOUR_APPR_PROCESS_START_y',
 'WEEKDAY_APPR_PROCESS_START',
 'NAME_TYPE_SUITE',
 'bureau_CREDIT_ACTIVE',
 'bureau_CREDIT_Closed',
 'bureau_CREDIT_Sold',
 'bureau_DAYS_CREDIT',
 'bureau_CREDIT_DAY_OVERDUE',
 'bureau_DAYS_CREDIT_ENDDATE',
 'bureau_DAYS_ENDDATE_FACT',
 'bureau_CNT_CREDIT_PROLONG',
 'bureau_AMT_CREDIT_SUM',
 'bureau_AMT_CREDIT_SUM_DEBT',
 'bureau_AMT_CREDIT_SUM_LIMIT',
 'bureau_AMT_CREDIT_SUM_OVERDUE',
 'bureau_CREDIT_TYPE_Car loan',
 'bureau_CREDIT_TYPE_Consumer credit',
 'bureau_CREDIT_TYPE_Credit card',
 'bureau_CREDIT_TYPE_Microloan',
 'bureau_CREDIT_TYPE_Mortgage',
 'bureau_DAYS_CREDIT_UPDATE',
 'bureau_CLOSE',
 'FLAG_DOCUMENT_RATIO',
 'NAN',
 'simple_labelx',
 'scores']

In [ ]:
SK_NUM_PREV、SK_ID_PREV_y、bureau_SK_ID_CURR

In [9]:
df=df.drop(df[['SK_ID_CURR','bureau_CREDIT_ACTIVE',
 'bureau_CREDIT_Closed',
 'bureau_CREDIT_Sold',
 'bureau_DAYS_CREDIT',
 'bureau_CREDIT_DAY_OVERDUE',
 'bureau_DAYS_CREDIT_ENDDATE',
 'bureau_DAYS_ENDDATE_FACT',
 'bureau_CNT_CREDIT_PROLONG',
 'bureau_AMT_CREDIT_SUM',
 'bureau_AMT_CREDIT_SUM_DEBT',
 'bureau_AMT_CREDIT_SUM_LIMIT',
 'bureau_AMT_CREDIT_SUM_OVERDUE',
 'bureau_CREDIT_TYPE_Car loan',
 'bureau_CREDIT_TYPE_Consumer credit',
 'bureau_CREDIT_TYPE_Credit card',
 'bureau_CREDIT_TYPE_Microloan',
 'bureau_CREDIT_TYPE_Mortgage',
 'bureau_DAYS_CREDIT_UPDATE',
 'bureau_CLOSE',
 'FLAG_DOCUMENT_RATIO',
 'NAN',]],axis=1)

In [10]:
df.head()

,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_EDUCATION_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,FLAG_EMP_PHONE,FLAG_WORK_PHONE,...,PORTFOLIO_Cash,PORTFOLIO_POS,YIELD_high,YIELD_low,YIELD_middle,HOUR_APPR_PROCESS_START_y,WEEKDAY_APPR_PROCESS_START,NAME_TYPE_SUITE,simple_labelx,scores
0,1.0,0.0,202500.0,1.0,-9461.0,-637.0,-3648.0,-2120.0,1.0,0.0,...,0.000000,1.000000,0.000000,1.000000,0.000000,9.0,6.0,0.0,0.0,96
1,0.0,0.0,270000.0,3.0,-16765.0,-1188.0,-1186.0,-291.0,1.0,0.0,...,0.333333,0.666667,0.000000,0.333333,0.666667,12.0,5.0,1.0,0.0,100
2,0.0,0.0,67500.0,1.0,-19046.0,-225.0,-4260.0,-2531.0,1.0,1.0,...,0.000000,1.000000,0.000000,0.000000,1.000000,5.0,5.0,0.0,0.0,100
3,0.0,0.0,135000.0,1.0,-19005.0,-3039.0,-9833.0,-2437.0,1.0,0.0,...,0.500000,0.333333,0.333333,0.333333,0.166667,15.0,4.0,0.0,0.0,96
4,0.0,0.0,121500.0,1.0,-19932.0,-3038.0,-4311.0,-3458.0,1.0,0.0,...,0.666667,0.333333,0.500000,0.000000,0.500000,13.0,7.0,0.0,0.0,88

In [11]:
df.to_csv('application_train_merge_clear_nomissing_with_ylabel.csv')

In [ ]:
df.