In [1]:
import pandas as pd
import numpy as np
#df_org=pd.read_csv(filepath+"application_train_merge_clear_nomissing .csv")
df_org=pd.read_csv("application_train_merge_clear_nomissing_with_ylabel_dy.csv")

In [2]:
df=df_org

In [22]:
y_=[]#找出 違約人的索引
for i in (df[df["simple_labelx"]!=0].index):
  y_.append(i)
y_1=[] #找出沒違約人的索引
for i in (df[df["simple_labelx"]==0].index):
  y_1.append(i)
df_split=df.loc[y_]
df_split0=df.loc[y_1]
df_tar1=df_split.reset_index()
df_tar0=df_split0.reset_index()
df_tar_e=df_tar0.iloc[:57886,:] #分成同等分
dfe=pd.concat([df_tar_e,df_tar1],ignore_index=True,axis=0)

In [23]:
df_X = dfe[['AMT_INCOME_TOTAL', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_REGISTRATION',
       'DAYS_ID_PUBLISH', 'CNT_FAM_MEMBERS', 'HOUR_APPR_PROCESS_START_x',
       'OBS_60_CNT_SOCIAL_CIRCLE', 'DAYS_LAST_PHONE_CHANGE',
       'AMT_REQ_CREDIT_BUREAU_YEAR']]
df_y = dfe['simple_labelx']

In [28]:
df_X=dfe[['DAYS_LAST_PHONE_CHANGE',
       'AMT_REQ_CREDIT_BUREAU_YEAR']]
df_y = dfe['simple_labelx']

In [ ]:
df_X = dfe[['AMT_INCOME_TOTAL',  'DAYS_REGISTRATION',
        'CNT_FAM_MEMBERS',
       'OBS_60_CNT_SOCIAL_CIRCLE']]
df_y = dfe['simple_labelx']

In [17]:
df.head()

,Unnamed: 0,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_EDUCATION_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,FLAG_EMP_PHONE,...,FONDKAPREMONT_MODE_reg oper account,FONDKAPREMONT_MODE_reg oper spec account,HOUSETYPE_MODE_block of flats,WALLSMATERIAL_MODE_Block,WALLSMATERIAL_MODE_Panel,"WALLSMATERIAL_MODE_Stone, brick",EMERGENCYSTATE_MODE_No,EMERGENCYSTATE_MODE_Yes,simple_labelx,scores
0,0,1.0,0.0,202500.0,1.0,-9461.0,-637.0,-3648.0,-2120.0,1.0,...,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,96
1,1,0.0,0.0,270000.0,3.0,-16765.0,-1188.0,-1186.0,-291.0,1.0,...,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,100
2,2,0.0,0.0,67500.0,1.0,-19046.0,-225.0,-4260.0,-2531.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100
3,3,0.0,0.0,135000.0,1.0,-19005.0,-3039.0,-9833.0,-2437.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,96
4,4,0.0,0.0,121500.0,1.0,-19932.0,-3038.0,-4311.0,-3458.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,88

In [29]:
from sklearn.model_selection import train_test_split
#X , y = dfe.iloc[:,2:-2] , dfe.iloc[:,-2]
X , y = df_X  , df_y
X_train, X_test, y_train, y_test =\
    train_test_split(X, y, 
                     test_size=0.1,#超過10萬9,1分比較好 
                     #random_state=0, 
                     stratify=y)

In [30]:
from xgboost import XGBClassifier

# 建立 XGBClassifier 模型
xgboostModel = XGBClassifier(n_estimators=100, learning_rate= 0.3)
# 使用訓練資料訓練模型
xgboostModel.fit(X_train, y_train)
# 使用訓練資料預測分類
predicted = xgboostModel.predict(X_train)

In [31]:
# 預測成功的比例
print('訓練集: ',xgboostModel.score(X_train,y_train))
print('測試集: ',xgboostModel.score(X_test,y_test))

訓練集:  0.6114171641361307
測試集:  0.5977716358611159

In [32]:
xgboostModel.feature_importances_

array([0.5102624 , 0.48973754], dtype=float32)